name = "playjonny-casino-com-pt"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=playjonny-casino.com.pt"
HMAC_KEY = "3f37429e78a66f56a7272a7cf28dcf979b748f951761d1f203db1e295666436f"
COOKIE_NAME = "p5l"
PLAY_PATH = "start-now"
BUTTON_ID = "pb0bc6116b2d8af942927baa3cc87fc5f"
GATE_SALT = "47daf8fb5f11696b"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "8tu0"
CTA_SELECTOR = ".play-button"
